manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nickconway
      url-base: https://github.com/nickconway
  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: dynamic-macro
      revision: main
      import: app/west.yml
  self:
    path: config
